/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    services: Service;
    'contact-submissions': ContactSubmission;
    faqs: Faq;
    testimonials: Testimonial;
    'special-module-entries': SpecialModuleEntry;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    'contact-submissions': ContactSubmissionsSelect<false> | ContactSubmissionsSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    'special-module-entries': SpecialModuleEntriesSelect<false> | SpecialModuleEntriesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    header: Header;
    footer: Footer;
    'home-page': HomePage;
    'about-page': AboutPage;
    'services-page': ServicesPage;
    'contact-page': ContactPage;
    'special-module-page': SpecialModulePage;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    'about-page': AboutPageSelect<false> | AboutPageSelect<true>;
    'services-page': ServicesPageSelect<false> | ServicesPageSelect<true>;
    'contact-page': ContactPageSelect<false> | ContactPageSelect<true>;
    'special-module-page': SpecialModulePageSelect<false> | SpecialModulePageSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  role: 'superadmin' | 'admin' | 'editor';
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: string | null;
  folder?: string | null;
  visibility: 'public' | 'private';
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  published?: boolean | null;
  title: string;
  homeOrder?: number | null;
  slug: string;
  summary: string;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  featuredImage?: (number | null) | Media;
  icon?: string | null;
  cardMeta?: string | null;
  isFeatured?: boolean | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    canonicalUrl?: string | null;
    /**
     * Selecciona una imagen existente desde Media Library o crea una nueva desde este mismo selector.
     */
    ogImage?: (number | null) | Media;
    noIndex?: boolean | null;
    schemaType?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions".
 */
export interface ContactSubmission {
  id: number;
  name: string;
  email: string;
  phone?: string | null;
  company?: string | null;
  message: string;
  sourcePage?: string | null;
  status: 'new' | 'in-review' | 'closed';
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  published?: boolean | null;
  question: string;
  answer: string;
  category?: string | null;
  relatedService?: (number | null) | Service;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  published?: boolean | null;
  name: string;
  role?: string | null;
  company?: string | null;
  quote: string;
  photo?: (number | null) | Media;
  isFeatured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "special-module-entries".
 */
export interface SpecialModuleEntry {
  id: number;
  title: string;
  slug?: string | null;
  publicCode: string;
  documentType?: string | null;
  documentNumber?: string | null;
  moduleStatus: 'active' | 'inactive' | 'expired';
  issuedAt?: string | null;
  expiresAt?: string | null;
  summary?: string | null;
  publicNotes?: string | null;
  internalNotes?: string | null;
  attachment?: (number | null) | Media;
  ownerName?: string | null;
  isPublic?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'contact-submissions';
        value: number | ContactSubmission;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'special-module-entries';
        value: number | SpecialModuleEntry;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  folder?: T;
  visibility?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  published?: T;
  title?: T;
  homeOrder?: T;
  slug?: T;
  summary?: T;
  content?: T;
  featuredImage?: T;
  icon?: T;
  cardMeta?: T;
  isFeatured?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        canonicalUrl?: T;
        ogImage?: T;
        noIndex?: T;
        schemaType?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions_select".
 */
export interface ContactSubmissionsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  company?: T;
  message?: T;
  sourcePage?: T;
  status?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  published?: T;
  question?: T;
  answer?: T;
  category?: T;
  relatedService?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  published?: T;
  name?: T;
  role?: T;
  company?: T;
  quote?: T;
  photo?: T;
  isFeatured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "special-module-entries_select".
 */
export interface SpecialModuleEntriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  publicCode?: T;
  documentType?: T;
  documentNumber?: T;
  moduleStatus?: T;
  issuedAt?: T;
  expiresAt?: T;
  summary?: T;
  publicNotes?: T;
  internalNotes?: T;
  attachment?: T;
  ownerName?: T;
  isPublic?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  siteTagline?: string | null;
  /**
   * Selecciona el logo desde Media Library o crea uno nuevo desde este mismo selector.
   */
  logo?: (number | null) | Media;
  /**
   * Texto alternativo del logo para accesibilidad y carga SEO básica.
   */
  logoAlt?: string | null;
  siteDescription?: string | null;
  domain?: string | null;
  /**
   * Correo principal publico para CTA, contacto y fallback editorial del sitio.
   */
  contactEmail?: string | null;
  contactPhone?: string | null;
  address?: string | null;
  socialLinks?:
    | {
        platform: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  branding?: {
    primaryColor?: string | null;
    secondaryColor?: string | null;
    accentColor?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  topbarText?: string | null;
  navItems?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  supportLabel?: string | null;
  supportValue?: string | null;
  cta: {
    label: string;
    url: string;
    variant: 'primary' | 'secondary';
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  summary?: string | null;
  address?: string | null;
  navigationLinks?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  contactLinks?:
    | {
        label: string;
        value: string;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  legalCta: {
    label: string;
    url: string;
    variant: 'primary' | 'secondary';
  };
  legalLinks?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  footerBadge?: string | null;
  copyright?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: number;
  hero: {
    eyebrow?: string | null;
    title: string;
    subtitle?: string | null;
    description?: string | null;
    /**
     * Slides opcionales del hero. Si se cargan, el frontend los puede usar como alternativa editorial sin romper el modelo actual.
     */
    slides?:
      | {
          label: string;
          title: string;
          description: string;
          /**
           * Selecciona una imagen existente desde Media Library o crea una nueva desde este mismo selector. Recomendado: formato horizontal y alta calidad.
           */
          image?: (number | null) | Media;
          alt?: string | null;
          visualBadge?: string | null;
          cornerLabel?: string | null;
          id?: string | null;
        }[]
      | null;
    visualBadge?: string | null;
    cornerLabel?: string | null;
    /**
     * Selecciona una imagen existente desde Media Library o crea una nueva desde este mismo selector. Recomendado: formato horizontal de alta calidad.
     */
    heroMedia?: (number | null) | Media;
    primaryCta: {
      label: string;
      url: string;
      variant: 'primary' | 'secondary';
    };
    secondaryCta: {
      label: string;
      url: string;
      variant: 'primary' | 'secondary';
    };
    trustItems?:
      | {
          value: string;
          label: string;
          id?: string | null;
        }[]
      | null;
  };
  statsBar?: {
    items?:
      | {
          value: string;
          label: string;
          id?: string | null;
        }[]
      | null;
  };
  servicesSection?: {
    eyebrow?: string | null;
    title?: string | null;
    description?: string | null;
  };
  aboutSection?: {
    eyebrow?: string | null;
    title?: string | null;
    description?: string | null;
    /**
     * Selecciona una imagen existente desde Media Library o crea una nueva desde este mismo selector. Ideal para hangar, equipo o foto institucional.
     */
    image?: (number | null) | Media;
    highlights?:
      | {
          value: string;
          id?: string | null;
        }[]
      | null;
  };
  certificationsSection?: {
    eyebrow?: string | null;
    title?: string | null;
    description?: string | null;
    items?:
      | {
          title: string;
          description: string;
          meta?: string | null;
          linkLabel?: string | null;
          linkUrl?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  pricingSection?: {
    eyebrow?: string | null;
    title?: string | null;
    description?: string | null;
    items?:
      | {
          badge?: string | null;
          title: string;
          description: string;
          cta: {
            label: string;
            url: string;
            variant: 'primary' | 'secondary';
          };
          id?: string | null;
        }[]
      | null;
  };
  industriesSection?: {
    eyebrow?: string | null;
    title?: string | null;
    description?: string | null;
    items?:
      | {
          title: string;
          description: string;
          meta?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  valuesSection?: {
    eyebrow?: string | null;
    title?: string | null;
    description?: string | null;
    items?:
      | {
          title: string;
          description: string;
          id?: string | null;
        }[]
      | null;
  };
  ctaBanner: {
    title?: string | null;
    description?: string | null;
    primaryCta: {
      label: string;
      url: string;
      variant: 'primary' | 'secondary';
    };
    secondaryCta: {
      label: string;
      url: string;
      variant: 'primary' | 'secondary';
    };
  };
  contactSection?: {
    eyebrow?: string | null;
    title?: string | null;
    description?: string | null;
  };
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    canonicalUrl?: string | null;
    /**
     * Selecciona una imagen existente desde Media Library o crea una nueva desde este mismo selector.
     */
    ogImage?: (number | null) | Media;
    noIndex?: boolean | null;
    schemaType?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page".
 */
export interface AboutPage {
  id: number;
  heroTitle: string;
  heroDescription?: string | null;
  storyTitle?: string | null;
  storyBody?: string | null;
  values?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    canonicalUrl?: string | null;
    /**
     * Selecciona una imagen existente desde Media Library o crea una nueva desde este mismo selector.
     */
    ogImage?: (number | null) | Media;
    noIndex?: boolean | null;
    schemaType?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services-page".
 */
export interface ServicesPage {
  id: number;
  heroTitle: string;
  heroDescription?: string | null;
  intro?: string | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    canonicalUrl?: string | null;
    ogImage?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page".
 */
export interface ContactPage {
  id: number;
  title: string;
  description?: string | null;
  formTitle?: string | null;
  formDescription?: string | null;
  formButtonLabel?: string | null;
  contactCards?:
    | {
        label: string;
        value: string;
        url?: string | null;
        ctaLabel?: string | null;
        id?: string | null;
      }[]
    | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    canonicalUrl?: string | null;
    /**
     * Selecciona una imagen existente desde Media Library o crea una nueva desde este mismo selector.
     */
    ogImage?: (number | null) | Media;
    noIndex?: boolean | null;
    schemaType?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "special-module-page".
 */
export interface SpecialModulePage {
  id: number;
  heroTitle: string;
  heroDescription?: string | null;
  inputLabel?: string | null;
  searchButtonLabel?: string | null;
  emptyStateMessage?: string | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    canonicalUrl?: string | null;
    ogImage?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  siteTagline?: T;
  logo?: T;
  logoAlt?: T;
  siteDescription?: T;
  domain?: T;
  contactEmail?: T;
  contactPhone?: T;
  address?: T;
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  branding?:
    | T
    | {
        primaryColor?: T;
        secondaryColor?: T;
        accentColor?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  topbarText?: T;
  navItems?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  supportLabel?: T;
  supportValue?: T;
  cta?:
    | T
    | {
        label?: T;
        url?: T;
        variant?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  summary?: T;
  address?: T;
  navigationLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  contactLinks?:
    | T
    | {
        label?: T;
        value?: T;
        url?: T;
        id?: T;
      };
  legalCta?:
    | T
    | {
        label?: T;
        url?: T;
        variant?: T;
      };
  legalLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  footerBadge?: T;
  copyright?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        subtitle?: T;
        description?: T;
        slides?:
          | T
          | {
              label?: T;
              title?: T;
              description?: T;
              image?: T;
              alt?: T;
              visualBadge?: T;
              cornerLabel?: T;
              id?: T;
            };
        visualBadge?: T;
        cornerLabel?: T;
        heroMedia?: T;
        primaryCta?:
          | T
          | {
              label?: T;
              url?: T;
              variant?: T;
            };
        secondaryCta?:
          | T
          | {
              label?: T;
              url?: T;
              variant?: T;
            };
        trustItems?:
          | T
          | {
              value?: T;
              label?: T;
              id?: T;
            };
      };
  statsBar?:
    | T
    | {
        items?:
          | T
          | {
              value?: T;
              label?: T;
              id?: T;
            };
      };
  servicesSection?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        description?: T;
      };
  aboutSection?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        description?: T;
        image?: T;
        highlights?:
          | T
          | {
              value?: T;
              id?: T;
            };
      };
  certificationsSection?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        description?: T;
        items?:
          | T
          | {
              title?: T;
              description?: T;
              meta?: T;
              linkLabel?: T;
              linkUrl?: T;
              id?: T;
            };
      };
  pricingSection?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        description?: T;
        items?:
          | T
          | {
              badge?: T;
              title?: T;
              description?: T;
              cta?:
                | T
                | {
                    label?: T;
                    url?: T;
                    variant?: T;
                  };
              id?: T;
            };
      };
  industriesSection?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        description?: T;
        items?:
          | T
          | {
              title?: T;
              description?: T;
              meta?: T;
              id?: T;
            };
      };
  valuesSection?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        description?: T;
        items?:
          | T
          | {
              title?: T;
              description?: T;
              id?: T;
            };
      };
  ctaBanner?:
    | T
    | {
        title?: T;
        description?: T;
        primaryCta?:
          | T
          | {
              label?: T;
              url?: T;
              variant?: T;
            };
        secondaryCta?:
          | T
          | {
              label?: T;
              url?: T;
              variant?: T;
            };
      };
  contactSection?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        description?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        canonicalUrl?: T;
        ogImage?: T;
        noIndex?: T;
        schemaType?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page_select".
 */
export interface AboutPageSelect<T extends boolean = true> {
  heroTitle?: T;
  heroDescription?: T;
  storyTitle?: T;
  storyBody?: T;
  values?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        canonicalUrl?: T;
        ogImage?: T;
        noIndex?: T;
        schemaType?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services-page_select".
 */
export interface ServicesPageSelect<T extends boolean = true> {
  heroTitle?: T;
  heroDescription?: T;
  intro?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        canonicalUrl?: T;
        ogImage?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page_select".
 */
export interface ContactPageSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  formTitle?: T;
  formDescription?: T;
  formButtonLabel?: T;
  contactCards?:
    | T
    | {
        label?: T;
        value?: T;
        url?: T;
        ctaLabel?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        canonicalUrl?: T;
        ogImage?: T;
        noIndex?: T;
        schemaType?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "special-module-page_select".
 */
export interface SpecialModulePageSelect<T extends boolean = true> {
  heroTitle?: T;
  heroDescription?: T;
  inputLabel?: T;
  searchButtonLabel?: T;
  emptyStateMessage?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        canonicalUrl?: T;
        ogImage?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}