/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    services: Service;
    faqs: Faq;
    testimonials: Testimonial;
    'contact-submissions': ContactSubmission;
    'special-module-entries': SpecialModuleEntry;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    'contact-submissions': ContactSubmissionsSelect<false> | ContactSubmissionsSelect<true>;
    'special-module-entries': SpecialModuleEntriesSelect<false> | SpecialModuleEntriesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    header: Header;
    footer: Footer;
    'home-page': HomePage;
    'about-page': AboutPage;
    'services-page': ServicesPage;
    'contact-page': ContactPage;
    'special-module-page': SpecialModulePage;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    'about-page': AboutPageSelect<false> | AboutPageSelect<true>;
    'services-page': ServicesPageSelect<false> | ServicesPageSelect<true>;
    'contact-page': ContactPageSelect<false> | ContactPageSelect<true>;
    'special-module-page': SpecialModulePageSelect<false> | SpecialModulePageSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'admin' | 'editor';
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: string | null;
  folder?: string | null;
  visibility: 'public' | 'private';
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  title: string;
  slug: string;
  summary: string;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  featuredImage?: (number | null) | Media;
  isFeatured?: boolean | null;
  metaTitle?: string | null;
  metaDescription?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  question: string;
  answer: string;
  category?: string | null;
  relatedService?: (number | null) | Service;
  isPublished?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  name: string;
  role?: string | null;
  company?: string | null;
  quote: string;
  photo?: (number | null) | Media;
  isFeatured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions".
 */
export interface ContactSubmission {
  id: number;
  name: string;
  email: string;
  phone?: string | null;
  message: string;
  sourcePage?: string | null;
  status: 'new' | 'reviewing' | 'closed';
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "special-module-entries".
 */
export interface SpecialModuleEntry {
  id: number;
  title: string;
  slug: string;
  publicCode: string;
  documentType: 'code' | 'dni' | 'ruc';
  documentNumber: string;
  status: 'active' | 'expired' | 'pending';
  issuedAt?: string | null;
  expiresAt?: string | null;
  ownerName?: string | null;
  publicSummary?: string | null;
  publicNotes?: string | null;
  /**
   * Uso interno. No debe exponerse en flujos públicos.
   */
  internalNotes?: string | null;
  attachment?: (number | null) | Media;
  isPublic?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'contact-submissions';
        value: number | ContactSubmission;
      } | null)
    | ({
        relationTo: 'special-module-entries';
        value: number | SpecialModuleEntry;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  folder?: T;
  visibility?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  summary?: T;
  content?: T;
  featuredImage?: T;
  isFeatured?: T;
  metaTitle?: T;
  metaDescription?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  category?: T;
  relatedService?: T;
  isPublished?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  company?: T;
  quote?: T;
  photo?: T;
  isFeatured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions_select".
 */
export interface ContactSubmissionsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  message?: T;
  sourcePage?: T;
  status?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "special-module-entries_select".
 */
export interface SpecialModuleEntriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  publicCode?: T;
  documentType?: T;
  documentNumber?: T;
  status?: T;
  issuedAt?: T;
  expiresAt?: T;
  ownerName?: T;
  publicSummary?: T;
  publicNotes?: T;
  internalNotes?: T;
  attachment?: T;
  isPublic?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  siteTagline?: string | null;
  siteUrl: string;
  businessSector?: string | null;
  branding?: {
    primaryColor?: string | null;
    secondaryColor?: string | null;
    accentColor?: string | null;
    logo?: (number | null) | Media;
  };
  contactInfo?: {
    email?: string | null;
    phone?: string | null;
    whatsApp?: string | null;
    address?: string | null;
  };
  defaultSeo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    canonicalUrl?: string | null;
    ogImage?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  showTopbar?: boolean | null;
  topbarText?: string | null;
  navItems?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  cta?: {
    label?: string | null;
    href?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  summary?: string | null;
  contactInfo?: {
    address?: string | null;
    email?: string | null;
    phone?: string | null;
  };
  navLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  legalLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: number;
  hero: {
    eyebrow?: string | null;
    title: string;
    subtitle?: string | null;
    description?: string | null;
    heroImage?: (number | null) | Media;
  };
  stats?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  servicesHighlightMode?: ('featured' | 'all') | null;
  servicesSection?: {
    eyebrow?: string | null;
    title?: string | null;
    description?: string | null;
  };
  aboutSection?: {
    eyebrow?: string | null;
    title?: string | null;
    description?: string | null;
  };
  certificationsSection?: {
    title?: string | null;
    description?: string | null;
  };
  pricingSection?: {
    title?: string | null;
    description?: string | null;
  };
  industriesSection?: {
    title?: string | null;
    description?: string | null;
  };
  valuesSection?: {
    title?: string | null;
    description?: string | null;
  };
  ctaBanner?: {
    title?: string | null;
    description?: string | null;
    label?: string | null;
    href?: string | null;
  };
  contactSection?: {
    title?: string | null;
    description?: string | null;
  };
  /**
   * Referencia CMS-friendly de la composición objetivo del home basada en el HTML aprobado.
   */
  homeReferenceSections?:
    | {
        section: string;
        id?: string | null;
      }[]
    | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    canonicalUrl?: string | null;
    ogImage?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page".
 */
export interface AboutPage {
  id: number;
  heroTitle: string;
  heroDescription?: string | null;
  story?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  values?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    canonicalUrl?: string | null;
    ogImage?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services-page".
 */
export interface ServicesPage {
  id: number;
  heroTitle: string;
  heroDescription?: string | null;
  intro?: string | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    canonicalUrl?: string | null;
    ogImage?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page".
 */
export interface ContactPage {
  id: number;
  heroTitle: string;
  heroDescription?: string | null;
  formIntro?: string | null;
  /**
   * Fragmento iframe o URL de mapa cuando el cliente lo confirme.
   */
  mapEmbed?: string | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    canonicalUrl?: string | null;
    ogImage?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "special-module-page".
 */
export interface SpecialModulePage {
  id: number;
  heroTitle: string;
  heroDescription?: string | null;
  inputLabel?: string | null;
  searchButtonLabel?: string | null;
  emptyStateMessage?: string | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    canonicalUrl?: string | null;
    ogImage?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  siteTagline?: T;
  siteUrl?: T;
  businessSector?: T;
  branding?:
    | T
    | {
        primaryColor?: T;
        secondaryColor?: T;
        accentColor?: T;
        logo?: T;
      };
  contactInfo?:
    | T
    | {
        email?: T;
        phone?: T;
        whatsApp?: T;
        address?: T;
      };
  defaultSeo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        canonicalUrl?: T;
        ogImage?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  showTopbar?: T;
  topbarText?: T;
  navItems?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  cta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  summary?: T;
  contactInfo?:
    | T
    | {
        address?: T;
        email?: T;
        phone?: T;
      };
  navLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  legalLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        subtitle?: T;
        description?: T;
        heroImage?: T;
      };
  stats?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  servicesHighlightMode?: T;
  servicesSection?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        description?: T;
      };
  aboutSection?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        description?: T;
      };
  certificationsSection?:
    | T
    | {
        title?: T;
        description?: T;
      };
  pricingSection?:
    | T
    | {
        title?: T;
        description?: T;
      };
  industriesSection?:
    | T
    | {
        title?: T;
        description?: T;
      };
  valuesSection?:
    | T
    | {
        title?: T;
        description?: T;
      };
  ctaBanner?:
    | T
    | {
        title?: T;
        description?: T;
        label?: T;
        href?: T;
      };
  contactSection?:
    | T
    | {
        title?: T;
        description?: T;
      };
  homeReferenceSections?:
    | T
    | {
        section?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        canonicalUrl?: T;
        ogImage?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page_select".
 */
export interface AboutPageSelect<T extends boolean = true> {
  heroTitle?: T;
  heroDescription?: T;
  story?: T;
  values?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        canonicalUrl?: T;
        ogImage?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services-page_select".
 */
export interface ServicesPageSelect<T extends boolean = true> {
  heroTitle?: T;
  heroDescription?: T;
  intro?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        canonicalUrl?: T;
        ogImage?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page_select".
 */
export interface ContactPageSelect<T extends boolean = true> {
  heroTitle?: T;
  heroDescription?: T;
  formIntro?: T;
  mapEmbed?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        canonicalUrl?: T;
        ogImage?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "special-module-page_select".
 */
export interface SpecialModulePageSelect<T extends boolean = true> {
  heroTitle?: T;
  heroDescription?: T;
  inputLabel?: T;
  searchButtonLabel?: T;
  emptyStateMessage?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        canonicalUrl?: T;
        ogImage?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}